### enpoint to test api
GET http://localhost:3001/users/login?username=Striker&email=test@mail.com&password=compaq

### enpoint to test api
GET http://localhost:3001/products/comprar?id=0,3,4,5,6,78,

###
POST http://localhost:3001/users/register
Content-Type: application/json

{
    "username": "Roja",
    "email": "Roja@mail.com",
    "password": "compaq",
    "name": "Michael",
    "lastname": "Cocuy"
}

### enpoint to get all users
GET http://localhost:3001/users/getAll

### enpoint to get all users
GET http://localhost:3001/users/getByUsername/striker


###
PUT http://localhost:3001/users/update/xd
Content-Type: application/json

{
    "username": "Roja",
    "email": "Roja@mail.com",
    "password": "compaq",
    "name": "Liz",
    "lastname": "Perez"
}

###
DELETE http://localhost:3001/users/delete/64f146376426b1fb2a1c898c
